### ISSUE TITLE
I dont know ML but I know grammar

### ISSUE THREAD

**Issue by erclu** [enricobu96/is_even_dl#3]
first of all twice, LuL

https://github.com/enricobu96/is_even_dl/blob/00bc02777dd368e8464560032938376edee37e69/README.md?plain=1#L15-L22

**Comment by enricobu96** [comment]
not a bug it's a feature close #3

**Comment by erclu** [comment]
🌭

**Comment by enricobu96** [comment]
> 🌭

🌭

**Comment by erclu** [comment]
> > 🌭
> 
> 🌭

🌭
